<a href="https://colab.research.google.com/github/ShrutiJain456/compute/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv(r"/content/data.csv")  #uploaded data file in colab itself and then copied the file path for no errors
df

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
0,0,0.01020,0.833,204600,0.434,0.021900,2,0.1650,-8.795,1,0.4310,150.062,4.0,0.286,1,Mask Off,Future
1,1,0.19900,0.743,326933,0.359,0.006110,1,0.1370,-10.401,1,0.0794,160.083,4.0,0.588,1,Redbone,Childish Gambino
2,2,0.03440,0.838,185707,0.412,0.000234,2,0.1590,-7.148,1,0.2890,75.044,4.0,0.173,1,Xanny Family,Future
3,3,0.60400,0.494,199413,0.338,0.510000,5,0.0922,-15.236,1,0.0261,86.468,4.0,0.230,1,Master Of None,Beach House
4,4,0.18000,0.678,392893,0.561,0.512000,5,0.4390,-11.648,0,0.0694,174.004,4.0,0.904,1,Parallel Lines,Junior Boys
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012,2012,0.00106,0.584,274404,0.932,0.002690,1,0.1290,-3.501,1,0.3330,74.976,4.0,0.211,0,Like A Bitch - Kill The Noise Remix,Kill The Noise
2013,2013,0.08770,0.894,182182,0.892,0.001670,1,0.0528,-2.663,1,0.1310,110.041,4.0,0.867,0,Candy,Dillon Francis
2014,2014,0.00857,0.637,207200,0.935,0.003990,0,0.2140,-2.467,1,0.1070,150.082,4.0,0.470,0,Habit - Dack Janiels & Wenzday Remix,Rain Man
2015,2015,0.00164,0.557,185600,0.992,0.677000,1,0.0913,-2.735,1,0.1330,150.011,4.0,0.623,0,First Contact,Twin Moons
2016,2016,0.00281,0.446,204520,0.915,0.000039,9,0.2180,-6.221,1,0.1410,190.013,4.0,0.402,0,I Wanna Get Better,Bleachers

In [ ]:
df.head() #head command gives a peek of first 5 rows(default value)

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
0,0,0.0102,0.833,204600,0.434,0.021900,2,0.1650,-8.795,1,0.4310,150.062,4.0,0.286,1,Mask Off,Future
1,1,0.1990,0.743,326933,0.359,0.006110,1,0.1370,-10.401,1,0.0794,160.083,4.0,0.588,1,Redbone,Childish Gambino
2,2,0.0344,0.838,185707,0.412,0.000234,2,0.1590,-7.148,1,0.2890,75.044,4.0,0.173,1,Xanny Family,Future
3,3,0.6040,0.494,199413,0.338,0.510000,5,0.0922,-15.236,1,0.0261,86.468,4.0,0.230,1,Master Of None,Beach House
4,4,0.1800,0.678,392893,0.561,0.512000,5,0.4390,-11.648,0,0.0694,174.004,4.0,0.904,1,Parallel Lines,Junior Boys

In [ ]:
df.head(10)  #user can write their required value in the bracket

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
0,0,0.01020,0.833,204600,0.434,0.021900,2,0.1650,-8.795,1,0.4310,150.062,4.0,0.286,1,Mask Off,Future
1,1,0.19900,0.743,326933,0.359,0.006110,1,0.1370,-10.401,1,0.0794,160.083,4.0,0.588,1,Redbone,Childish Gambino
2,2,0.03440,0.838,185707,0.412,0.000234,2,0.1590,-7.148,1,0.2890,75.044,4.0,0.173,1,Xanny Family,Future
3,3,0.60400,0.494,199413,0.338,0.510000,5,0.0922,-15.236,1,0.0261,86.468,4.0,0.230,1,Master Of None,Beach House
4,4,0.18000,0.678,392893,0.561,0.512000,5,0.4390,-11.648,0,0.0694,174.004,4.0,0.904,1,Parallel Lines,Junior Boys
5,5,0.00479,0.804,251333,0.560,0.000000,8,0.1640,-6.682,1,0.1850,85.023,4.0,0.264,1,Sneakin’,Drake
6,6,0.01450,0.739,241400,0.472,0.000007,1,0.2070,-11.204,1,0.1560,80.030,4.0,0.308,1,Childs Play,Drake
7,7,0.02020,0.266,349667,0.348,0.664000,10,0.1600,-11.609,0,0.0371,144.154,4.0,0.393,1,Gyöngyhajú lány,Omega
8,8,0.04810,0.603,202853,0.944,0.000000,11,0.3420,-3.626,0,0.3470,130.035,4.0,0.398,1,I've Seen Footage,Death Grips
9,9,0.00208,0.836,226840,0.603,0.000000,7,0.5710,-7.792,1,0.2370,99.994,4.0,0.386,1,Digital Animal,Honey Claws

In [ ]:
df.tail() #tail command gives a peek of rows from the end (5 is the default value)

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
2012,2012,0.00106,0.584,274404,0.932,0.002690,1,0.1290,-3.501,1,0.333,74.976,4.0,0.211,0,Like A Bitch - Kill The Noise Remix,Kill The Noise
2013,2013,0.08770,0.894,182182,0.892,0.001670,1,0.0528,-2.663,1,0.131,110.041,4.0,0.867,0,Candy,Dillon Francis
2014,2014,0.00857,0.637,207200,0.935,0.003990,0,0.2140,-2.467,1,0.107,150.082,4.0,0.470,0,Habit - Dack Janiels & Wenzday Remix,Rain Man
2015,2015,0.00164,0.557,185600,0.992,0.677000,1,0.0913,-2.735,1,0.133,150.011,4.0,0.623,0,First Contact,Twin Moons
2016,2016,0.00281,0.446,204520,0.915,0.000039,9,0.2180,-6.221,1,0.141,190.013,4.0,0.402,0,I Wanna Get Better,Bleachers

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
2012,2012,0.00106,0.584,274404,0.932,0.002690,1,0.1290,-3.501,1,0.333,74.976,4.0,0.211,0,Like A Bitch - Kill The Noise Remix,Kill The Noise
2013,2013,0.08770,0.894,182182,0.892,0.001670,1,0.0528,-2.663,1,0.131,110.041,4.0,0.867,0,Candy,Dillon Francis
2014,2014,0.00857,0.637,207200,0.935,0.003990,0,0.2140,-2.467,1,0.107,150.082,4.0,0.470,0,Habit - Dack Janiels & Wenzday Remix,Rain Man
2015,2015,0.00164,0.557,185600,0.992,0.677000,1,0.0913,-2.735,1,0.133,150.011,4.0,0.623,0,First Contact,Twin Moons
2016,2016,0.00281,0.446,204520,0.915,0.000039,9,0.2180,-6.221,1,0.141,190.013,4.0,0.402,0,I Wanna Get Better,Bleachers

In [ ]:
df.tail(9) #we can ask for our required value in the bracket

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
2008,2008,0.054100,0.646,160408,0.714,0.000000,0,0.1340,-6.511,1,0.0378,97.957,4.0,0.589,0,"Call On Me - EDWYNN X TIKAL, Spirix Remix",Starley
2009,2009,0.004990,0.595,224000,0.837,0.035900,1,0.1010,-6.011,1,0.0696,149.964,4.0,0.331,0,Aamon,Kuuro
2010,2010,0.002310,0.624,206013,0.971,0.121000,6,0.2550,-0.935,0,0.0643,102.003,4.0,0.442,0,Hey Baby - Steve Aoki Remix,Dimitri Vegas & Like Mike
2011,2011,0.000586,0.528,245053,0.879,0.004890,6,0.0432,-5.891,0,0.1200,128.268,4.0,0.327,0,Brightside - Borgeous Remix,Icona Pop
2012,2012,0.001060,0.584,274404,0.932,0.002690,1,0.1290,-3.501,1,0.3330,74.976,4.0,0.211,0,Like A Bitch - Kill The Noise Remix,Kill The Noise
2013,2013,0.087700,0.894,182182,0.892,0.001670,1,0.0528,-2.663,1,0.1310,110.041,4.0,0.867,0,Candy,Dillon Francis
2014,2014,0.008570,0.637,207200,0.935,0.003990,0,0.2140,-2.467,1,0.1070,150.082,4.0,0.470,0,Habit - Dack Janiels & Wenzday Remix,Rain Man
2015,2015,0.001640,0.557,185600,0.992,0.677000,1,0.0913,-2.735,1,0.1330,150.011,4.0,0.623,0,First Contact,Twin Moons
2016,2016,0.002810,0.446,204520,0.915,0.000039,9,0.2180,-6.221,1,0.1410,190.013,4.0,0.402,0,I Wanna Get Better,Bleachers

In [ ]:
df.info() 
#info command gives us info abt no. of null/non null values and dtype of the columns 
#in our dataset, it shows 2017 non null entries for all the 17 columns and data type of each column  **doubt

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2017 entries, 0 to 2016
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        2017 non-null   int64
 1   acousticness      2017 non-null   float64
 2   danceability      2017 non-null   float64
 3   duration_ms       2017 non-null   int64
 4   energy            2017 non-null   float64
 5   instrumentalness  2017 non-null   float64
 6   key               2017 non-null   int64
 7   liveness          2017 non-null   float64
 8   loudness          2017 non-null   float64
 9   mode              2017 non-null   int64
 10  speechiness       2017 non-null   float64
 11  tempo             2017 non-null   float64
 12  time_signature    2017 non-null   float64
 13  valence           2017 non-null   float64
 14  target            2017 non-null   int64
 15  song_title        2017 non-null   object
 16  artist            2017 non-null   object
dtypes: float64(10), int64(5), object(2)
memory usage: 268.0+ KB

In [ ]:
#we can use any attribute command as per our requirement #for eg.we wish to see just the data type of each column 
df.dtypes #**doubt : series object not callable when used()

Unnamed: 0            int64
acousticness        float64
danceability        float64
duration_ms           int64
energy              float64
instrumentalness    float64
key                   int64
liveness            float64
loudness            float64
mode                  int64
speechiness         float64
tempo               float64
time_signature      float64
valence             float64
target                int64
song_title           object
artist               object
dtype: object

In [ ]:
df.sort_values('danceability')[['song_title', 'artist']].head(10)

,song_title,artist
729,Bumpy Road,Destruction Unit
532,Wake Bake Skate,FIDLAR
817,"Mozart: Requiem in D Minor, K. 626: VIII. Lacr...",Nikolaus Harnoncourt
1600,"Trio Sonata in G Major, Wq. 144: I. Adagio",Carl Philipp Emanuel Bach
1598,"Piano Quartet in E flat, Op.47: 3. Andante can...",Robert Schumann
522,Outro,M83
1348,Be My Valentine (feat. Dickie Allen),Brojob
1464,Right Here,Keys N Krates
1313,Senseless Order,Signs of the Swarm
1306,Ruin,Altered Perceptions

In [ ]:
df.sort_values('duration_ms')[['song_title', 'duration_ms', 'artist']].tail(10)

,song_title,duration_ms,artist
1602,"String Quintet in C Major, Op. 29: II. Adagio ...",649415,Ludwig van Beethoven
304,Night on Bald Mountain,659560,Modest Mussorgsky
858,Night on Bald Mountain,700027,Modest Mussorgsky
404,Who Is He And What Is He To You,703107,Creative Source
335,Zombie,745653,Fela Kuti
1565,Gloomy Sunday,763467,Branford Marsalis
1603,Viola Sonata in C Minor: III. Andante con vari...,784013,Felix Mendelssohn
819,Southern Man - Live,825027,"Crosby, Stills, Nash & Young"
695,Music Is the Answer - Original Extended 12-Inc...,849960,Celeda
1535,The Nearness of You,1004627,Joshua Redman

In [ ]:
df_new = df[df['duration_ms'] < 400000]
df_new

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
0,0,0.01020,0.833,204600,0.434,0.021900,2,0.1650,-8.795,1,0.4310,150.062,4.0,0.286,1,Mask Off,Future
1,1,0.19900,0.743,326933,0.359,0.006110,1,0.1370,-10.401,1,0.0794,160.083,4.0,0.588,1,Redbone,Childish Gambino
2,2,0.03440,0.838,185707,0.412,0.000234,2,0.1590,-7.148,1,0.2890,75.044,4.0,0.173,1,Xanny Family,Future
3,3,0.60400,0.494,199413,0.338,0.510000,5,0.0922,-15.236,1,0.0261,86.468,4.0,0.230,1,Master Of None,Beach House
4,4,0.18000,0.678,392893,0.561,0.512000,5,0.4390,-11.648,0,0.0694,174.004,4.0,0.904,1,Parallel Lines,Junior Boys
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012,2012,0.00106,0.584,274404,0.932,0.002690,1,0.1290,-3.501,1,0.3330,74.976,4.0,0.211,0,Like A Bitch - Kill The Noise Remix,Kill The Noise
2013,2013,0.08770,0.894,182182,0.892,0.001670,1,0.0528,-2.663,1,0.1310,110.041,4.0,0.867,0,Candy,Dillon Francis
2014,2014,0.00857,0.637,207200,0.935,0.003990,0,0.2140,-2.467,1,0.1070,150.082,4.0,0.470,0,Habit - Dack Janiels & Wenzday Remix,Rain Man
2015,2015,0.00164,0.557,185600,0.992,0.677000,1,0.0913,-2.735,1,0.1330,150.011,4.0,0.623,0,First Contact,Twin Moons
2016,2016,0.00281,0.446,204520,0.915,0.000039,9,0.2180,-6.221,1,0.1410,190.013,4.0,0.402,0,I Wanna Get Better,Bleachers

In [ ]:
df_new1 = df_new.sort_values('energy')[['song_title', 'artist', 'duration_ms',]].tail(10)
df_new1

               song_title                    artist  duration_ms  energy
1296         Black Colors       Victim Of Deception       247533   0.990
1681                Hated                 Beartooth       211430   0.990
1328  Down into the Abyss               Conjonctive       256920   0.991
1680             Paranoia         A Day To Remember       200677   0.992
1332      Beautiful Agony          Within The Ruins       271560   0.992
2015        First Contact                Twin Moons       185600   0.992
1347           Unanswered           Suicide Silence       135653   0.993
1297    A Darkened Gospel      A Wake in Providence       311217   0.994
1322           Pitchblack  Walking Dead On Broadway       221776   0.997
1299        No Absolution         Thy Art Is Murder       201783   0.998

In [ ]:
ans = df_new1.sort_values('energy', ascending=False)
ans

               song_title                    artist  duration_ms  energy
1299        No Absolution         Thy Art Is Murder       201783   0.998
1322           Pitchblack  Walking Dead On Broadway       221776   0.997
1297    A Darkened Gospel      A Wake in Providence       311217   0.994
1347           Unanswered           Suicide Silence       135653   0.993
1680             Paranoia         A Day To Remember       200677   0.992
1332      Beautiful Agony          Within The Ruins       271560   0.992
2015        First Contact                Twin Moons       185600   0.992
1328  Down into the Abyss               Conjonctive       256920   0.991
1296         Black Colors       Victim Of Deception       247533   0.990
1681                Hated                 Beartooth       211430   0.990

In [ ]:
df_new.to_csv = (r'/content/data.csv')

In [ ]:
#activity 1
df_1 = df[df['energy'] > 0.4]['song_title']
df_1

0                                   Mask Off
2                               Xanny Family
4                             Parallel Lines
5                                   Sneakin’
6                                Childs Play
                        ...
2012     Like A Bitch - Kill The Noise Remix
2013                                   Candy
2014    Habit - Dack Janiels & Wenzday Remix
2015                           First Contact
2016                      I Wanna Get Better
Name: song_title, Length: 1830, dtype: object

In [ ]:
#activity 2
df_2 = df[df['duration_ms'] < 300000]
df_3 = df_2.sort_values('tempo', ascending = False)[['song_title', 'artist']].head(10)
df_3

                song_title            artist
124       Danger and Dread        Brown Bird
718            Hannah Hunt   Vampire Weekend
1960            Puppy Love      Donny Osmond
1711               Amazing     Big Time Rush
809        Tupelo - Part 1       Pop Staples
826     Living Every Dream            Antwon
1339  The Shaping Sickness  Shadow of Intent
102         Willing & Able        Disclosure
1802             Mad Love.              JoJo
532        Wake Bake Skate            FIDLAR

In [ ]:
#activity 3
df_11 = df[df['artist'] == 'Drake'] 
df_m = df_11[df_11['energy'] > 0.5]['song_title']
df_m

5                      Sneakin’
37                      Jumpman
117               Hotline Bling
154                   Big Rings
440                   Headlines
589     Started From the Bottom
779     0 To 100 / The Catch Up
1016           Skepta Interlude
1218            Best I Ever Had
1223                  Take Care
Name: song_title, dtype: object